// install REST Client extension in VSCode
@baseUrl=http://127.0.0.1:8081

### health check
GET {{baseUrl}}/health

### Create Account
POST {{baseUrl}}/accounts
Content-Type: application/json

{
    "owner": "hsykyh",
    "currency": "EUR"
}

### Get Account
GET {{baseUrl}}/accounts/147

### List Accounts
GET http://localhost:8081/accounts?page_id=1&page_size=10
