// install REST Client extension in VSCode
@baseUrl=http://127.0.0.1:8081

### health check
GET {{baseUrl}}/health

### Create Account
POST {{baseUrl}}/accounts
Content-Type: application/json

{
    "owner": "John Doe 4",
    "currency": "CAD"
}

### Get Account
GET {{baseUrl}}/accounts/147

### List Accounts
GET http://localhost:8081/accounts?page_id=1&page_size=10

### Create Transfers
POST {{baseUrl}}/transfers
Content-Type: application/json

{
    "from_account_id": 146,
    "to_account_id": 147,
    "amount": 10,
    "currency": "USD"
}
