version: '3.8'

services:
  db:
    image: postgres:15
    container_name: simplebank_db
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "${DB_PORT}:5432"

  app:
    build: .
    container_name: simplebank_app
    env_file:
      - .env
    ports:
      - "${APP_PORT}:8081"
    depends_on:
      - db
    stdin_open: true
    tty: true
    command: [ "/app/main" ]

volumes:
  db_data:
